// This file has been automatically generated by zap-es.
import * as $ from "zap-es";
export const _zapFileId = 0xe3fca095c1cb2e87n;
export class BigIntBag extends $.Struct {
  static readonly _zap = {
    displayName: "BigIntBag",
    id: "86748469b18e4943",
    size: new $.ObjectSize(32, 0),
    defaultDefaultSigned: $.getInt64Mask(-0xdb4da5f7ef412b1n),
    defaultDefaultUnsigned: $.getUint64Mask(0xdb4da5f7ef412b1n)
  };
  get signed(): bigint {
    return $.utils.getInt64(0, this);
  }
  set signed(value: bigint) {
    $.utils.setInt64(0, value, this);
  }
  get unsigned(): bigint {
    return $.utils.getUint64(8, this);
  }
  set unsigned(value: bigint) {
    $.utils.setUint64(8, value, this);
  }
  get defaultSigned(): bigint {
    return $.utils.getInt64(16, this, BigIntBag._zap.defaultDefaultSigned);
  }
  set defaultSigned(value: bigint) {
    $.utils.setInt64(16, value, this, BigIntBag._zap.defaultDefaultSigned);
  }
  get defaultUnsigned(): bigint {
    return $.utils.getUint64(24, this, BigIntBag._zap.defaultDefaultUnsigned);
  }
  set defaultUnsigned(value: bigint) {
    $.utils.setUint64(24, value, this, BigIntBag._zap.defaultDefaultUnsigned);
  }
  toString(): string { return "BigIntBag_" + super.toString(); }
}
