// This file has been automatically generated by zap-es.
import * as $ from "zap-es";
export const _zapFileId = 0xe0b7ff464fbc7ee2n;
export class Foo extends $.Struct {
  static readonly _zap = {
    displayName: "Foo",
    id: "ebf41ad8c4cd4576",
    size: new $.ObjectSize(0, 2),
  };
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  get baz(): string {
    return $.utils.getText(1, this);
  }
  set baz(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "Foo_" + super.toString(); }
}
