// This file has been automatically generated by zap-es.
import * as $ from "zap-es";
export const _zapFileId = 0xe0b7ff464fbc7ee1n;
export class Foo extends $.Struct {
  static readonly _zap = {
    displayName: "Foo",
    id: "9e8e6186e9348688",
    size: new $.ObjectSize(0, 1),
  };
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "Foo_" + super.toString(); }
}
