// This file has been automatically generated by zap-es.
import * as $ from "zap-es";
import { Foo } from "./import-foo.js";
export const _zapFileId = 0x9cbc682922e84ff9n;
export class Baz extends $.Struct {
  static readonly FOO_CONST = $.readRawPointer(new Uint8Array([16, 2, 64, 1, 0, 0]).buffer);
  static readonly _zap = {
    displayName: "Baz",
    id: "f2f28862b8e82db7",
    size: new $.ObjectSize(0, 1),
  };
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "Baz_" + super.toString(); }
}
